### ISSUE TITLE
Thick Jail

### ISSUE THREAD

**Issue by david8001** [fractalcells/ansible-iocage#20]
Hi,

iocage support the creation of thick jail. It seems after looking at the source, that it is not yet support here. As i am more a sys adm than a developper, would it be possible to add this feature the same way you add the basejail feature?

It would be much appriciated.

Regards,

David

**Comment by xmj** [comment]
Hi David,

Thanks for your ticket. The support for thick jails isn't there because I've never used them through iocage.
If someone else would like to contribute the code and provide tests, I'm happy to merge it.

Thanks
Johannes

**Comment by david8001** [comment]
i made some modification on the iocage file and i am now testing it. but i do not now how to submit it through git once i have done the tests

**Comment by xmj** [comment]
This might be a good introductory post: https://opensource.com/article/19/7/create-pull-request-github

**Comment by david8001** [comment]
$ git push -u origin thick
remote: Permission to fractalcells/ansible-iocage.git denied to david8001.
fatal: unable to access 'https://github.com/fractalcells/ansible-iocage/': The requested URL returned error: 403

Thick is the name of the branch i created locally
??

**Comment by david8001** [comment]
thank you. i just done my pull request :-)
