### ISSUE TITLE
Changes lgtm :+1: but it now conflicts with what I've merved from #35 - could you please your changes on master branch?

### ISSUE THREAD

**Issue by vbotka** [fractalcells/ansible-iocage#37]
Changes lgtm :+1: but it now conflicts with what I've merved from #35 - could you please your changes on master branch?

You don't need to open a new pull request for this, just do `git checkout master ;  git pull origin master ; git checkout fix-start-stop ; git rebase -i master ; git push --force origin fix-start-stop` or something along these lines

_Originally posted by @xmj in https://github.com/fractalcells/ansible-iocage/issues/36#issuecomment-908877394_

**Comment by xmj** [comment]
What's the issue for?

**Comment by vbotka** [comment]
Disregard, please. Sorry for the noise.

**Comment by xmj** [comment]
Np, thanks for you work :-)
