### ISSUE TITLE
"iocage: release" is not idempotent.

### ISSUE THREAD

**Issue by Infiniverse** [fractalcells/ansible-iocage#4]
When downloading a release with iocell, it isn't idempotent - it will extract the release again each time it is run:

    - name: Check if our iocell release has been downloaded
      iocell: state=fetched release="{{ iocage_release | default(omit) }}"
      check_mode: no

This is probably because iocell itself reextracts the release each time.

However, ansible should be idempotent, and do nothing if the work has already been done.

Perhaps ansible-iocell should be taught to look at 'iocell list -r' first, to determine whether it needs to do anything.

**Comment by xmj** [comment]
Nice catch, I'll take a look at fixing it.
