### ISSUE TITLE
Properties and Ansible 2.5.5

### ISSUE THREAD

**Issue by aperum** [fractalcells/ansible-iocage#7]
Hi,

i'm trying to create a new jail with properties, like this:

```
- name: Ensure jail is present
  iocage:
    state="{{ jail_state }}"
    name="{{ jail_name }}"
    release="{{ jail_release }}"
    properties={ ip4_addr="{{ jail_ipv4 }}", ip6_addr="{{ jail_ipv6 }}", host_hostname="{{ jail_hostname }}" }
  tags:
    - iocage
```
Which  gives this error:

```
ERROR! this task 'iocage' has extra params, which is only allowed in the following modules: command, win_command, shell, win_shell, script, include, include_vars, include_tasks, include_role, import_tasks, import_role, add_host, group_by, set_fact, raw, meta

The error appears to have been in '/root/ansible/roles/jails/tasks/main.yml': line 10, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
- name: Ensure jail is present
  ^ here
```

Changing the line to dict notation:

```
properties={ ip4_addr: "{{ jail_ipv4 }}", ip6_addr: "{{ jail_ipv6 }}", host_hostname: "{{ jail_hostname }}" }
```

 throws another error:

```
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed here
The error appears to have been in '/root/ansible/roles/jails/tasks/main.yml': line 22, column 26, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    release="{{ jail_release }}"
    properties={ ip4_addr: "{{ jail_ipv4 }}", ip6_addr: "{{ jail_ipv6 }}", host_hostname: "{{ jail_hostname }}" }
                         ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:
    with_items:
      - {{ foo }}
Should be written as:
    with_items:
      - "{{ foo }}"
```

Addendum: This is with Ansible 2.5.5 (Python 2.7.15) on FreeBSD 11.2

**Comment by richardbowden** [comment]
I had that issue, but found if you use a yaml dict like so, it works. ensure to use spaces not tabs for spacing

`- name: create jail
  iocage: 
    name: "foo" 
    state: "present"
    properties:
      ip4_addr: 172.16.0.1
      boot: 'on'
      allow_sysvipc: 1
      defaultrouter: "10.1.0.1"
`

**Comment by aperum** [comment]
Thanks for the hint! I'll try at the next time a jail needs to be updated.

**Comment by xmj** [comment]
@aperum could you verify that @berenddeboer's solution works for you?

**Comment by aperum** [comment]
This will take a while as i went forward with an alternative implementation of the jail setup. I hope to get back to this within the next two weeks.

**Comment by aperum** [comment]
I'm sorry, but i won't have any time in the foreseeable future to try this. Feel free to close this report for now. I'll report back if i get the time to work on this again.

**Comment by xmj** [comment]
Thanks for reporting back. Closing this for the time being...
